<?php
// Iniciar sesión para verificar si el usuario está logeado
session_start();

// Verificar si el usuario está logeado
if (!isset($_SESSION['user_id'])) {
    // Si no está logeado, redirigir al login
    header("Location: join.html");
    exit;
}

?>

<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Página Principal</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
  <div class="container mt-5">
    <h2 class="text-center">Bienvenido a tu página principal</h2>
    <p class="text-center">¡Hola, <?php echo $_SESSION['user_username']; ?>! Estás logeado.</p>

    <?php
    // botón para cerrar sesión
      if (isset ( $_POST ["logout"] )) {
          session_destroy();
          $redirectPageUrl= "join.html";
          header("Location: ".$redirectPageUrl);
      }
    ?>
    
    <div class="container text-center">
      <form role="form" method="post">
          <div class="pull-right-container">
              <i class="icon fa fa-user"> 
              <input type="submit" value="Cerrar Sesión"
                  class="btn btn-danger" name="logout" />
              </i>
          </div>
      </form>
    </div>
    
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>