<?php
// Iniciar sesión para verificar si el usuario está ya logeado

session_start();

// Comprobamos el rol del usuario si existe
if(isset($_SESSION['user_role']) && $_SESSION['user_role'] == 2 ){
  header("Location: index.phtml");
  exit;
}
// Comprobamos el rol del usuario si existe
if(isset($_SESSION['user_role']) && $_SESSION['user_role'] == 1 ){
  header("Location: dashboard.phtml");
  exit;
}

if(isset($_GET["success"])){
  // Seteamos variable success con valores de _GET["success"]
  $success = $_GET["success"];

  // Mensajes en función del success
  if($success == 1){
    $msg = "El usuario ha sido creado correctamente, logeate cuando quieras.";
  }
}

if(isset($_GET["error"])){
  // Seteamos variable error con valores de _GET["error"]
  $error = $_GET["error"];
  
  // Mensajes en función del error
  if($error == 1){
    $msg = "Su nombre de usuario no cumple con los requisitos establecidos, utilice sólo 'aA09-_'";
  }
  if($error == 2){
    $msg = "Necesitas iniciar sesión primero";
  }
  if($error == 3){
    $msg = "Por favor, complete todos los campos.";
  }
  if($error == 4){
    $msg = "Usuario o contraseña incorrectos.";
  }
  if($error == 5){
    $msg = "No estás autorizado para acceder a este sitio.";
  }
  if($error == 6){
    $msg = "Error inesperado, vuelva a intentarlo más tarde o contacte con soporte técnico 666-666-666.";
  }
}

?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Formulario de Login</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
  <div class="container mt-5 w-50">
    <h2 class="text-center">Login</h2>
    <form class="mt-5" action="login_validate.php" method="POST">
      <div class="mb-3">
        <label for="name" class="form-label">Nombre de Usuario</label>
        <input type="text" class="form-control" id="name" name="name">
        
        <?php if(isset($error) && $error == 1): ?>
          <p class="fs-6 mb-3 mt-3 text-danger">
            <?=$msg?>
          </p>
        <?php endif;?>

      </div>
      <div class="mb-3">
        <label for="password" class="form-label">Contraseña</label>
        <input type="password" class="form-control" id="password" name="password">
      </div>

      <?php if(isset($error) && $error == 6 || isset($error) && $error == 5 || isset($error) && $error == 1 || isset($error) && $error == 2 || isset($error) && $error == 3 || isset($error) && $error == 4): ?>
        <p class="fs-6 mb-3 mt-3 text-danger">
          <?=$msg?>
        </p>
      <?php endif;?>

      <?php if(isset($success) && $success == 1): ?>
          <p class="fs-6 mb-3 mt-5 text-success">
            <?=$msg?>
          </p>
      <?php endif;?>

      <button type="submit" class="btn btn-primary w-100">Iniciar Sesión</button>
    </form>
    <div class="mt-5">
            <a href="sign.phtml" class="btn btn-success w-100">Registrarse</a>
        </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
