<?php 
if(isset($_GET["error"])){
  // Seteamos variable error con valores de _GET["error"]
  $error = $_GET["error"];
  // Mensajes en función del error
  if($error == 1){
    $msg = "Su nombre de usuario no cumple con los requisitos establecidos, 
    utilice sólo 'aA09-_' y debe tener una longitud de 6 a 16 caracteres.";
  }
  if($error == 2){
    $msg = "Las contraseñas no coinciden.";
  }
  if($error == 3){
    $msg = "Por favor, complete todos los campos.";
  }
  if($error == 4){
    $msg = "Su contraseña no cumple con los criterios de seguridad necesarios, 
    debe contener Mayusculas, minusculas, números y caracteres especiales, 
    y debe tener una longitud de 10 a 32 caracteres";
  }
  if($error == 5){
    $msg = "El email introducido no es un email válido. 
    Debe ser parecido a example@email.com";
  }
  if($error == 6){
    $msg = "Error inesperado, vuelva a intentarlo más tarde o 
    contacte con soporte técnico 666-666-666.";
  }
  if($error == 7){
    $msg = "Este nombre de usuario o email ya está registrado, escoge otro.";
  }
}

?>
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Formulario de Registro</title>
  <!-- Enlace a la hoja de estilos de Bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
  <div class="container mt-5" style="max-width: 500px;">
    <h2 class="text-center">Registro de Usuario</h2>
    <form action="signin_validate.php" method="POST"> 
      <div class="mb-3 mt-5">
        <label for="name" class="form-label">Nombre de usuario</label>
        <input type="text" class="form-control" id="name" name="name">
        <?php if(isset($error) && $error == 1): ?>
          <p class="fs-6 mb-3 mt-2 text-danger">
            <?= $msg ?>
          </p>
        <?php endif;?>
      </div>
      <div class="mb-3">
        <label for="email" class="form-label">email</label>
        <input type="text" class="form-control" id="email" name="email" required>
        <?php if(isset($error) && $error == 5): ?>
          <p class="fs-6 mb-3 mt-2 text-danger">
            <?= $msg ?>
          </p>
        <?php endif;?>
      </div>
      <div class="mb-3">
        <label for="password" class="form-label">Contraseña</label>
        <input type="password" class="form-control" id="password" name="password" required>
        <?php if(isset($error) && $error == 2): ?>
          <p class="fs-6 mb-3 mt-2 text-danger">
            <?= $msg ?>
          </p>
        <?php endif;?>
      </div>
      <div class="mb-3">
        <label for="confirmed_password" class="form-label">Confirmar Contraseña</label>
        <input type="password" class="form-control" id="confirmed_password" name="confirmed_password" required>
        <?php if(isset($error) && $error == 2): ?>
          <p class="fs-6 mb-3 mt-2 text-danger">
            <?= $msg ?>
          </p>
        <?php endif;?>
      </div>
      <button type="submit" class="btn btn-primary w-100">Registrarse</button>
      <?php if(isset($error) && $error == 6 || isset($error) && $error == 3 || isset($error) && $error == 4 || isset($error) && $error == 7): ?>
        <p class="fs-6 mb-3 mt-2 text-danger">
          <?= $msg ?>
        </p>
      <?php endif;?>
    </form>
    <div class="mt-5">
      <a href="login.phtml" class="btn btn-success w-100">Login</a>
    </div>
  </div>

  <!-- Enlace a los scripts de Bootstrap -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
